### ISSUE TITLE
Progress: Audio

### ISSUE THREAD

**Issue by xen0n** [xen0n/android_device_meizu_arale#2]
Tracking progress of audio subsystem porting in complement to #1.

**Comment by xen0n** [comment]
Starting point:

```
# output of `grep -i audio` from logcat

I/AudioFlinger(  263): Using default 3000 mSec as standby time.
E/BootAnimation(  445): couldn't find audio_conf.txt
W/BootAnimation(  445): Audio service is not initiated.
I/AudioPolicyService(  263): AudioPolicyService CSTOR in new mode
I/AudioPolicyManager(  263): loadAudioPolicyConfig() loaded /system/etc/audio_policy.conf
E/        (  263): MTK Audio loadLibrary() failed to open dlopen failed: library "libaudio.primary.default.so" not found
E/AudioFlinger(  263): int android::load_audio_interface(const char*, audio_hw_device_t**) couldn't open audio hw device in audio.primary (Operation not permitted)
I/AudioFlinger(  263): loadHwModule() error -1 loading module primary 
W/AudioPolicyManager(  263): could not open HW module primary
E/AudioFlinger(  263): int android::load_audio_interface(const char*, audio_hw_device_t**) couldn't load audio hw module audio.a2dp (No such file or directory)
I/AudioFlinger(  263): loadHwModule() error -2 loading module a2dp 
W/AudioPolicyManager(  263): could not open HW module a2dp
E/AudioFlinger(  263): int android::load_audio_interface(const char*, audio_hw_device_t**) couldn't load audio hw module audio.usb (No such file or directory)
I/AudioFlinger(  263): loadHwModule() error -2 loading module usb 
W/AudioPolicyManager(  263): could not open HW module usb
I/r_submix(  263): adev_open(name=audio_hw_if)
I/AudioFlinger(  263): loadHwModule() Loaded r_submix audio interface from Wifi Display audio HAL (audio) handle 1
D/r_submix(  263): submix_audio_device_create_pipe_l(addr=0, idx=9)
I/AudioFlinger(  263): AudioFlinger's thread 0xb58dc000 ready to run
D/r_submix(  263): submix_audio_device_release_pipe_l(idx=9) addr=0
D/r_submix(  263): submix_audio_device_destroy_pipe_l(): pipe destroyed
W/AudioPolicyManager(  263): Input device 00000002 unreachable
W/AudioPolicyManager(  263): Input device 00000001 unreachable
W/AudioPolicyManager(  263): Input device 80000004 unreachable
E/AudioPolicyManager(  263): Default device 00000002 is unreachable
E/AudioPolicyManager(  263): Failed to open primary output
E/AudioPolicyManager(  263): getDeviceForStrategy() speaker device not found for STRATEGY_SONIFICATION
E/AudioPolicyManager(  263): getDeviceForStrategy() speaker device not found for STRATEGY_SONIFICATION
E/AudioPolicyManager(  263): getDeviceForStrategy() no device found for STRATEGY_TRANSMITTED_THROUGH_SPEAKER
I/InputManager(  846): Initializing input manager, mUseDevInputEventForAudioJack=false
I/SystemServer(  846): Audio Service
E/AudioPolicyManager(  263): getDeviceForStrategy() speaker device not found for STRATEGY_SONIFICATION
E/AudioPolicyManager(  263): getDeviceForStrategy() speaker device not found for STRATEGY_SONIFICATION
E/AudioPolicyManager(  263): getDeviceForStrategy() speaker device not found for STRATEGY_SONIFICATION
E/AudioPolicyManager(  263): getDeviceForStrategy() speaker device not found for STRATEGY_SONIFICATION
E/AudioPolicyManager(  263): getDeviceForStrategy() no device found for STRATEGY_TRANSMITTED_THROUGH_SPEAKER
E/AudioPolicyManager(  263): getDeviceForStrategy() speaker device not found for STRATEGY_SONIFICATION
E/AudioPolicyManager(  263): getDeviceForStrategy() speaker device not found for STRATEGY_SONIFICATION
E/AudioPolicyManager(  263): getDeviceForStrategy() speaker device not found for STRATEGY_SONIFICATION
E/AudioPolicyManager(  263): getDeviceForStrategy() speaker device not found for STRATEGY_SONIFICATION
E/AudioPolicyManager(  263): getDeviceForStrategy() no device found for STRATEGY_TRANSMITTED_THROUGH_SPEAKER
W/WiredAccessoryManager(  846): This kernel does not have usb audio support
W/WiredAccessoryManager(  846): This kernel does not have HDMI audio support
I/FFMPEG  (  263):     Stream #0:0: Audio: vorbis, 44100 Hz, stereo, fltp, 160 kb/s
I/FFmpegExtractor(  263): adjust mime(application/ogg -> audio/vorbis)
D/FFmpegExtractor(  263): ffmpeg detected media content as 'audio/vorbis' with confidence 0.08
W/Utils   (  263): bool android::canOffloadStream(const android::sp<android::MetaData>&, bool, const android::sp<android::MetaData>&, bool, audio_stream_type_t) No sample bit depth info in meta data
E/AudioPolicyManager(  263): isOffloadSupported: stream_type != MUSIC, returning false
I/NuPlayer(  263): Could not offload audio decode, pcm offload decided :0
W/Utils   (  263): bool android::canOffloadStream(const android::sp<android::MetaData>&, bool, const android::sp<android::MetaData>&, bool, audio_stream_type_t) No sample bit depth info in meta data
E/AudioPolicyManager(  263): isOffloadSupported: stream_type != MUSIC, returning false
E/OMX     (  263): FAILED to allocate omx component 'OMX.MTK.AUDIO.DECODER.MP3'
E/OMX     (  263): FAILED to allocate omx component 'OMX.MTK.AUDIO.DECODER.ADPCM.MS'
E/OMX     (  263): FAILED to allocate omx component 'OMX.MTK.AUDIO.DECODER.ADPCM.DVI'
E/OMX     (  263): FAILED to allocate omx component 'OMX.MTK.AUDIO.DECODER.GSM'
E/OMX     (  263): FAILED to allocate omx component 'OMX.MTK.AUDIO.DECODER.G711.ALAW'
E/OMX     (  263): FAILED to allocate omx component 'OMX.MTK.AUDIO.DECODER.G711.MLAW'
E/OMX     (  263): FAILED to allocate omx component 'OMX.MTK.AUDIO.DECODER.FLAC'
E/OMX     (  263): FAILED to allocate omx component 'OMX.MTK.AUDIO.DECODER.WMA'
E/OMX     (  263): FAILED to allocate omx component 'OMX.MTK.AUDIO.DECODER.WMAPRO'
E/OMX     (  263): FAILED to allocate omx component 'OMX.MTK.AUDIO.ENCODER.VORBIS'
E/OMX     (  263): FAILED to allocate omx component 'OMX.MTK.AUDIO.ENCODER.ADPCM.MS'
E/OMX     (  263): FAILED to allocate omx component 'OMX.MTK.AUDIO.ENCODER.ADPCM.DVI'
I/FFMPEG  (  263):     Stream #0:0: Audio: vorbis, 44100 Hz, stereo, fltp, 160 kb/s
I/FFmpegExtractor(  263): adjust mime(application/ogg -> audio/vorbis)
D/FFmpegExtractor(  263): ffmpeg detected media content as 'audio/vorbis' with confidence 0.08
W/Utils   (  263): bool android::canOffloadStream(const android::sp<android::MetaData>&, bool, const android::sp<android::MetaData>&, bool, audio_stream_type_t) No sample bit depth info in meta data
E/AudioPolicyManager(  263): isOffloadSupported: stream_type != MUSIC, returning false
I/NuPlayer(  263): Could not offload audio decode, pcm offload decided :0
W/Utils   (  263): bool android::canOffloadStream(const android::sp<android::MetaData>&, bool, const android::sp<android::MetaData>&, bool, audio_stream_type_t) No sample bit depth info in meta data
E/AudioPolicyManager(  263): isOffloadSupported: stream_type != MUSIC, returning false
I/FFMPEG  (  263):     Stream #0:0: Audio: vorbis, 48000 Hz, stereo, fltp, 160 kb/s
I/FFmpegExtractor(  263): adjust mime(application/ogg -> audio/vorbis)
D/FFmpegExtractor(  263): ffmpeg detected media content as 'audio/vorbis' with confidence 0.08
W/Utils   (  263): bool android::canOffloadStream(const android::sp<android::MetaData>&, bool, const android::sp<android::MetaData>&, bool, audio_stream_type_t) No sample bit depth info in meta data
E/AudioPolicyManager(  263): isOffloadSupported: stream_type != MUSIC, returning false
I/NuPlayer(  263): Could not offload audio decode, pcm offload decided :0
W/Utils   (  263): bool android::canOffloadStream(const android::sp<android::MetaData>&, bool, const android::sp<android::MetaData>&, bool, audio_stream_type_t) No sample bit depth info in meta data
E/AudioPolicyManager(  263): isOffloadSupported: stream_type != MUSIC, returning false
I/FFMPEG  (  263):     Stream #0:0: Audio: vorbis, 48000 Hz, stereo, fltp, 96 kb/s
I/FFmpegExtractor(  263): adjust mime(application/ogg -> audio/vorbis)
D/FFmpegExtractor(  263): ffmpeg detected media content as 'audio/vorbis' with confidence 0.08
W/Utils   (  263): bool android::canOffloadStream(const android::sp<android::MetaData>&, bool, const android::sp<android::MetaData>&, bool, audio_stream_type_t) No sample bit depth info in meta data
E/AudioPolicyManager(  263): isOffloadSupported: stream_type != MUSIC, returning false
I/NuPlayer(  263): Could not offload audio decode, pcm offload decided :0
W/Utils   (  263): bool android::canOffloadStream(const android::sp<android::MetaData>&, bool, const android::sp<android::MetaData>&, bool, audio_stream_type_t) No sample bit depth info in meta data
E/AudioPolicyManager(  263): isOffloadSupported: stream_type != MUSIC, returning false
I/FFMPEG  (  263):     Stream #0:0: Audio: vorbis, 48000 Hz, mono, fltp, 140 kb/s
I/FFmpegExtractor(  263): adjust mime(application/ogg -> audio/vorbis)
D/FFmpegExtractor(  263): ffmpeg detected media content as 'audio/vorbis' with confidence 0.08
W/Utils   (  263): bool android::canOffloadStream(const android::sp<android::MetaData>&, bool, const android::sp<android::MetaData>&, bool, audio_stream_type_t) No sample bit depth info in meta data
E/AudioPolicyManager(  263): isOffloadSupported: stream_type != MUSIC, returning false
I/NuPlayer(  263): Could not offload audio decode, pcm offload decided :0
W/Utils   (  263): bool android::canOffloadStream(const android::sp<android::MetaData>&, bool, const android::sp<android::MetaData>&, bool, audio_stream_type_t) No sample bit depth info in meta data
E/AudioPolicyManager(  263): isOffloadSupported: stream_type != MUSIC, returning false
I/FFMPEG  (  263):     Stream #0:0: Audio: vorbis, 48000 Hz, mono, fltp, 140 kb/s
I/FFmpegExtractor(  263): adjust mime(application/ogg -> audio/vorbis)
D/FFmpegExtractor(  263): ffmpeg detected media content as 'audio/vorbis' with confidence 0.08
W/Utils   (  263): bool android::canOffloadStream(const android::sp<android::MetaData>&, bool, const android::sp<android::MetaData>&, bool, audio_stream_type_t) No sample bit depth info in meta data
E/AudioPolicyManager(  263): isOffloadSupported: stream_type != MUSIC, returning false
I/NuPlayer(  263): Could not offload audio decode, pcm offload decided :0
W/Utils   (  263): bool android::canOffloadStream(const android::sp<android::MetaData>&, bool, const android::sp<android::MetaData>&, bool, audio_stream_type_t) No sample bit depth info in meta data
E/AudioPolicyManager(  263): isOffloadSupported: stream_type != MUSIC, returning false
I/FFMPEG  (  263):     Stream #0:0: Audio: vorbis, 48000 Hz, mono, fltp, 140 kb/s
I/FFmpegExtractor(  263): adjust mime(application/ogg -> audio/vorbis)
D/FFmpegExtractor(  263): ffmpeg detected media content as 'audio/vorbis' with confidence 0.08
W/Utils   (  263): bool android::canOffloadStream(const android::sp<android::MetaData>&, bool, const android::sp<android::MetaData>&, bool, audio_stream_type_t) No sample bit depth info in meta data
E/AudioPolicyManager(  263): isOffloadSupported: stream_type != MUSIC, returning false
I/NuPlayer(  263): Could not offload audio decode, pcm offload decided :0
W/Utils   (  263): bool android::canOffloadStream(const android::sp<android::MetaData>&, bool, const android::sp<android::MetaData>&, bool, audio_stream_type_t) No sample bit depth info in meta data
E/AudioPolicyManager(  263): isOffloadSupported: stream_type != MUSIC, returning false
I/FFMPEG  (  263):     Stream #0:0: Audio: vorbis, 48000 Hz, mono, fltp, 140 kb/s
I/FFmpegExtractor(  263): adjust mime(application/ogg -> audio/vorbis)
D/FFmpegExtractor(  263): ffmpeg detected media content as 'audio/vorbis' with confidence 0.08
W/Utils   (  263): bool android::canOffloadStream(const android::sp<android::MetaData>&, bool, const android::sp<android::MetaData>&, bool, audio_stream_type_t) No sample bit depth info in meta data
E/AudioPolicyManager(  263): isOffloadSupported: stream_type != MUSIC, returning false
I/NuPlayer(  263): Could not offload audio decode, pcm offload decided :0
W/Utils   (  263): bool android::canOffloadStream(const android::sp<android::MetaData>&, bool, const android::sp<android::MetaData>&, bool, audio_stream_type_t) No sample bit depth info in meta data
E/AudioPolicyManager(  263): isOffloadSupported: stream_type != MUSIC, returning false
I/FFMPEG  (  263):     Stream #0:0: Audio: vorbis, 44100 Hz, mono, fltp, 239 kb/s
I/FFmpegExtractor(  263): adjust mime(application/ogg -> audio/vorbis)
D/FFmpegExtractor(  263): ffmpeg detected media content as 'audio/vorbis' with confidence 0.08
W/Utils   (  263): bool android::canOffloadStream(const android::sp<android::MetaData>&, bool, const android::sp<android::MetaData>&, bool, audio_stream_type_t) No sample bit depth info in meta data
E/AudioPolicyManager(  263): isOffloadSupported: stream_type != MUSIC, returning false
I/NuPlayer(  263): Could not offload audio decode, pcm offload decided :0
W/Utils   (  263): bool android::canOffloadStream(const android::sp<android::MetaData>&, bool, const android::sp<android::MetaData>&, bool, audio_stream_type_t) No sample bit depth info in meta data
E/AudioPolicyManager(  263): isOffloadSupported: stream_type != MUSIC, returning false
I/ActivityManager(  846): Start proc 1310:org.cyanogenmod.audiofx/u0a0 for added application org.cyanogenmod.audiofx
E/AudioPolicyManager(  263): getDeviceForStrategy() speaker device not found for STRATEGY_SONIFICATION
E/AudioPolicyManager(  263): getDeviceForStrategy() speaker device not found for STRATEGY_SONIFICATION
E/AudioPolicyManager(  263): getDeviceForStrategy() speaker device not found for STRATEGY_SONIFICATION
E/AudioPolicyManager(  263): getDeviceForStrategy() speaker device not found for STRATEGY_SONIFICATION
E/AudioPolicyManager(  263): getDeviceForStrategy() no device found for STRATEGY_TRANSMITTED_THROUGH_SPEAKER
E/AudioFlinger(  263): createEffect() unknown output thread
E/AudioEffect( 1310): set(): AudioFlinger could not create effect, status: -22
E/AudioEffects-JNI( 1310): AudioEffect initCheck failed -4
E/AudioEffect-JAVA( 1310): Error code -4 when initializing AudioEffect.
E/HeadsetService( 1310):    at android.media.audiofx.AudioEffect.<init>(AudioEffect.java:404)
E/HeadsetService( 1310):    at android.media.audiofx.Equalizer.<init>(Equalizer.java:139)
E/HeadsetService( 1310):    at org.cyanogenmod.audiofx.HeadsetService$EffectSet.<init>(HeadsetService.java:87)
E/HeadsetService( 1310):    at org.cyanogenmod.audiofx.HeadsetService.saveDefaults(HeadsetService.java:414)
E/HeadsetService( 1310):    at org.cyanogenmod.audiofx.HeadsetService.onCreate(HeadsetService.java:331)
W/AudioPolicyManager(  263): getOutput() could not find output for stream 1, samplingRate 0,format 0, channels 3, flags 0
W/AudioPolicyManager(  263): getOutput() could not find output for stream 1, samplingRate 0,format 0, channels 3, flags 0
W/AudioPolicyManager(  263): getOutput() could not find output for stream 1, samplingRate 44100,format 1, channels 3, flags 4
E/AudioTrack(  958): Could not get audio output for stream type 1, usage 0, sample rate 44100, format 0x1, channel mask 0x3, flags 0x4
E/SoundPool(  958): Error creating AudioTrack
W/AudioPolicyManager(  263): getOutput() could not find output for stream 1, samplingRate 0,format 0, channels 3, flags 0
W/AudioPolicyManager(  263): getOutput() could not find output for stream 1, samplingRate 0,format 0, channels 3, flags 0
W/AudioPolicyManager(  263): getOutput() could not find output for stream 1, samplingRate 48000,format 1, channels 3, flags 4
E/AudioTrack(  846): Could not get audio output for stream type 1, usage 0, sample rate 48000, format 0x1, channel mask 0x3, flags 0x4
E/SoundPool(  846): Error creating AudioTrack
I/MediaFocusControl(  846):  AudioFocus  abandonAudioFocus() from android.media.AudioManager@4d1253ccom.cyanogenmod.eleven.MusicPlaybackService$5@ecd52c5
I/MediaFocusControl(  846):  AudioFocus  abandonAudioFocus() from android.media.AudioManager@4d1253ccom.cyanogenmod.eleven.MusicPlaybackService$5@ecd52c5
```

**Comment by xen0n** [comment]
After adding prebuilt libraries`libtfa9890_interface.so` and `libtinyxml.so`...

```
I/AudioFlinger(  263): Using default 3000 mSec as standby time.
E/BootAnimation(  439): couldn't find audio_conf.txt
W/BootAnimation(  439): Audio service is not initiated.
I/AudioPolicyService(  263): AudioPolicyService CSTOR in new mode
I/AudioPolicyManager(  263): loadAudioPolicyConfig() loaded /system/etc/audio_policy.conf
E/        (  263): MTK Audio loadLibrary() failed to open dlopen failed: cannot locate symbol "_ZN7android11AudioSystem24getVoiceUnlockDLInstanceEv" referenced by "libaudio.primary.default.so"...
E/AudioFlinger(  263): int android::load_audio_interface(const char*, audio_hw_device_t**) couldn't open audio hw device in audio.primary (Operation not permitted)
I/AudioFlinger(  263): loadHwModule() error -1 loading module primary 
W/AudioPolicyManager(  263): could not open HW module primary
E/AudioFlinger(  263): int android::load_audio_interface(const char*, audio_hw_device_t**) couldn't load audio hw module audio.a2dp (No such file or directory)
I/AudioFlinger(  263): loadHwModule() error -2 loading module a2dp 
W/AudioPolicyManager(  263): could not open HW module a2dp
E/AudioFlinger(  263): int android::load_audio_interface(const char*, audio_hw_device_t**) couldn't load audio hw module audio.usb (No such file or directory)
I/AudioFlinger(  263): loadHwModule() error -2 loading module usb 
W/AudioPolicyManager(  263): could not open HW module usb
I/r_submix(  263): adev_open(name=audio_hw_if)
I/AudioFlinger(  263): loadHwModule() Loaded r_submix audio interface from Wifi Display audio HAL (audio) handle 1
D/r_submix(  263): submix_audio_device_create_pipe_l(addr=0, idx=9)
I/AudioFlinger(  263): AudioFlinger's thread 0xb58dc000 ready to run
D/r_submix(  263): submix_audio_device_release_pipe_l(idx=9) addr=0
D/r_submix(  263): submix_audio_device_destroy_pipe_l(): pipe destroyed
W/AudioPolicyManager(  263): Input device 00000002 unreachable
W/AudioPolicyManager(  263): Input device 00000001 unreachable
W/AudioPolicyManager(  263): Input device 80000004 unreachable
E/AudioPolicyManager(  263): Default device 00000002 is unreachable
E/AudioPolicyManager(  263): Failed to open primary output
E/AudioPolicyManager(  263): getDeviceForStrategy() speaker device not found for STRATEGY_SONIFICATION
E/AudioPolicyManager(  263): getDeviceForStrategy() speaker device not found for STRATEGY_SONIFICATION
E/AudioPolicyManager(  263): getDeviceForStrategy() no device found for STRATEGY_TRANSMITTED_THROUGH_SPEAKER
I/InputManager(  852): Initializing input manager, mUseDevInputEventForAudioJack=false
I/SystemServer(  852): Audio Service
E/AudioPolicyManager(  263): getDeviceForStrategy() speaker device not found for STRATEGY_SONIFICATION
E/AudioPolicyManager(  263): getDeviceForStrategy() speaker device not found for STRATEGY_SONIFICATION
E/AudioPolicyManager(  263): getDeviceForStrategy() speaker device not found for STRATEGY_SONIFICATION
E/AudioPolicyManager(  263): getDeviceForStrategy() speaker device not found for STRATEGY_SONIFICATION
E/AudioPolicyManager(  263): getDeviceForStrategy() no device found for STRATEGY_TRANSMITTED_THROUGH_SPEAKER
E/AudioPolicyManager(  263): getDeviceForStrategy() speaker device not found for STRATEGY_SONIFICATION
E/AudioPolicyManager(  263): getDeviceForStrategy() speaker device not found for STRATEGY_SONIFICATION
E/AudioPolicyManager(  263): getDeviceForStrategy() speaker device not found for STRATEGY_SONIFICATION
E/AudioPolicyManager(  263): getDeviceForStrategy() speaker device not found for STRATEGY_SONIFICATION
E/AudioPolicyManager(  263): getDeviceForStrategy() no device found for STRATEGY_TRANSMITTED_THROUGH_SPEAKER
W/WiredAccessoryManager(  852): This kernel does not have usb audio support
W/WiredAccessoryManager(  852): This kernel does not have HDMI audio support
I/FFMPEG  (  263):     Stream #0:0: Audio: vorbis, 44100 Hz, stereo, fltp, 160 kb/s
I/FFmpegExtractor(  263): adjust mime(application/ogg -> audio/vorbis)
D/FFmpegExtractor(  263): ffmpeg detected media content as 'audio/vorbis' with confidence 0.08
W/Utils   (  263): bool android::canOffloadStream(const android::sp<android::MetaData>&, bool, const android::sp<android::MetaData>&, bool, audio_stream_type_t) No sample bit depth info in meta data
E/AudioPolicyManager(  263): isOffloadSupported: stream_type != MUSIC, returning false
I/NuPlayer(  263): Could not offload audio decode, pcm offload decided :0
W/Utils   (  263): bool android::canOffloadStream(const android::sp<android::MetaData>&, bool, const android::sp<android::MetaData>&, bool, audio_stream_type_t) No sample bit depth info in meta data
E/AudioPolicyManager(  263): isOffloadSupported: stream_type != MUSIC, returning false
E/OMX     (  263): FAILED to allocate omx component 'OMX.MTK.AUDIO.DECODER.MP3'
E/OMX     (  263): FAILED to allocate omx component 'OMX.MTK.AUDIO.DECODER.ADPCM.MS'
E/OMX     (  263): FAILED to allocate omx component 'OMX.MTK.AUDIO.DECODER.ADPCM.DVI'
E/OMX     (  263): FAILED to allocate omx component 'OMX.MTK.AUDIO.DECODER.GSM'
E/OMX     (  263): FAILED to allocate omx component 'OMX.MTK.AUDIO.DECODER.G711.ALAW'
E/OMX     (  263): FAILED to allocate omx component 'OMX.MTK.AUDIO.DECODER.G711.MLAW'
E/OMX     (  263): FAILED to allocate omx component 'OMX.MTK.AUDIO.DECODER.FLAC'
E/OMX     (  263): FAILED to allocate omx component 'OMX.MTK.AUDIO.DECODER.WMA'
E/OMX     (  263): FAILED to allocate omx component 'OMX.MTK.AUDIO.DECODER.WMAPRO'
E/OMX     (  263): FAILED to allocate omx component 'OMX.MTK.AUDIO.ENCODER.VORBIS'
E/OMX     (  263): FAILED to allocate omx component 'OMX.MTK.AUDIO.ENCODER.ADPCM.MS'
E/OMX     (  263): FAILED to allocate omx component 'OMX.MTK.AUDIO.ENCODER.ADPCM.DVI'
I/FFMPEG  (  263):     Stream #0:0: Audio: vorbis, 44100 Hz, stereo, fltp, 160 kb/s
I/FFmpegExtractor(  263): adjust mime(application/ogg -> audio/vorbis)
D/FFmpegExtractor(  263): ffmpeg detected media content as 'audio/vorbis' with confidence 0.08
W/Utils   (  263): bool android::canOffloadStream(const android::sp<android::MetaData>&, bool, const android::sp<android::MetaData>&, bool, audio_stream_type_t) No sample bit depth info in meta data
E/AudioPolicyManager(  263): isOffloadSupported: stream_type != MUSIC, returning false
I/NuPlayer(  263): Could not offload audio decode, pcm offload decided :0
W/Utils   (  263): bool android::canOffloadStream(const android::sp<android::MetaData>&, bool, const android::sp<android::MetaData>&, bool, audio_stream_type_t) No sample bit depth info in meta data
E/AudioPolicyManager(  263): isOffloadSupported: stream_type != MUSIC, returning false
I/FFMPEG  (  263):     Stream #0:0: Audio: vorbis, 48000 Hz, stereo, fltp, 160 kb/s
I/FFmpegExtractor(  263): adjust mime(application/ogg -> audio/vorbis)
D/FFmpegExtractor(  263): ffmpeg detected media content as 'audio/vorbis' with confidence 0.08
W/Utils   (  263): bool android::canOffloadStream(const android::sp<android::MetaData>&, bool, const android::sp<android::MetaData>&, bool, audio_stream_type_t) No sample bit depth info in meta data
E/AudioPolicyManager(  263): isOffloadSupported: stream_type != MUSIC, returning false
I/NuPlayer(  263): Could not offload audio decode, pcm offload decided :0
W/Utils   (  263): bool android::canOffloadStream(const android::sp<android::MetaData>&, bool, const android::sp<android::MetaData>&, bool, audio_stream_type_t) No sample bit depth info in meta data
E/AudioPolicyManager(  263): isOffloadSupported: stream_type != MUSIC, returning false
I/FFMPEG  (  263):     Stream #0:0: Audio: vorbis, 48000 Hz, stereo, fltp, 96 kb/s
I/FFmpegExtractor(  263): adjust mime(application/ogg -> audio/vorbis)
D/FFmpegExtractor(  263): ffmpeg detected media content as 'audio/vorbis' with confidence 0.08
W/Utils   (  263): bool android::canOffloadStream(const android::sp<android::MetaData>&, bool, const android::sp<android::MetaData>&, bool, audio_stream_type_t) No sample bit depth info in meta data
E/AudioPolicyManager(  263): isOffloadSupported: stream_type != MUSIC, returning false
I/NuPlayer(  263): Could not offload audio decode, pcm offload decided :0
W/Utils   (  263): bool android::canOffloadStream(const android::sp<android::MetaData>&, bool, const android::sp<android::MetaData>&, bool, audio_stream_type_t) No sample bit depth info in meta data
E/AudioPolicyManager(  263): isOffloadSupported: stream_type != MUSIC, returning false
I/FFMPEG  (  263):     Stream #0:0: Audio: vorbis, 48000 Hz, mono, fltp, 140 kb/s
I/FFmpegExtractor(  263): adjust mime(application/ogg -> audio/vorbis)
D/FFmpegExtractor(  263): ffmpeg detected media content as 'audio/vorbis' with confidence 0.08
W/Utils   (  263): bool android::canOffloadStream(const android::sp<android::MetaData>&, bool, const android::sp<android::MetaData>&, bool, audio_stream_type_t) No sample bit depth info in meta data
E/AudioPolicyManager(  263): isOffloadSupported: stream_type != MUSIC, returning false
I/NuPlayer(  263): Could not offload audio decode, pcm offload decided :0
W/Utils   (  263): bool android::canOffloadStream(const android::sp<android::MetaData>&, bool, const android::sp<android::MetaData>&, bool, audio_stream_type_t) No sample bit depth info in meta data
E/AudioPolicyManager(  263): isOffloadSupported: stream_type != MUSIC, returning false
I/FFMPEG  (  263):     Stream #0:0: Audio: vorbis, 48000 Hz, mono, fltp, 140 kb/s
I/FFmpegExtractor(  263): adjust mime(application/ogg -> audio/vorbis)
D/FFmpegExtractor(  263): ffmpeg detected media content as 'audio/vorbis' with confidence 0.08
W/Utils   (  263): bool android::canOffloadStream(const android::sp<android::MetaData>&, bool, const android::sp<android::MetaData>&, bool, audio_stream_type_t) No sample bit depth info in meta data
E/AudioPolicyManager(  263): isOffloadSupported: stream_type != MUSIC, returning false
I/NuPlayer(  263): Could not offload audio decode, pcm offload decided :0
W/Utils   (  263): bool android::canOffloadStream(const android::sp<android::MetaData>&, bool, const android::sp<android::MetaData>&, bool, audio_stream_type_t) No sample bit depth info in meta data
E/AudioPolicyManager(  263): isOffloadSupported: stream_type != MUSIC, returning false
I/FFMPEG  (  263):     Stream #0:0: Audio: vorbis, 48000 Hz, mono, fltp, 140 kb/s
I/FFmpegExtractor(  263): adjust mime(application/ogg -> audio/vorbis)
D/FFmpegExtractor(  263): ffmpeg detected media content as 'audio/vorbis' with confidence 0.08
W/Utils   (  263): bool android::canOffloadStream(const android::sp<android::MetaData>&, bool, const android::sp<android::MetaData>&, bool, audio_stream_type_t) No sample bit depth info in meta data
E/AudioPolicyManager(  263): isOffloadSupported: stream_type != MUSIC, returning false
I/NuPlayer(  263): Could not offload audio decode, pcm offload decided :0
W/Utils   (  263): bool android::canOffloadStream(const android::sp<android::MetaData>&, bool, const android::sp<android::MetaData>&, bool, audio_stream_type_t) No sample bit depth info in meta data
E/AudioPolicyManager(  263): isOffloadSupported: stream_type != MUSIC, returning false
I/FFMPEG  (  263):     Stream #0:0: Audio: vorbis, 48000 Hz, mono, fltp, 140 kb/s
I/FFmpegExtractor(  263): adjust mime(application/ogg -> audio/vorbis)
D/FFmpegExtractor(  263): ffmpeg detected media content as 'audio/vorbis' with confidence 0.08
W/Utils   (  263): bool android::canOffloadStream(const android::sp<android::MetaData>&, bool, const android::sp<android::MetaData>&, bool, audio_stream_type_t) No sample bit depth info in meta data
E/AudioPolicyManager(  263): isOffloadSupported: stream_type != MUSIC, returning false
I/NuPlayer(  263): Could not offload audio decode, pcm offload decided :0
W/Utils   (  263): bool android::canOffloadStream(const android::sp<android::MetaData>&, bool, const android::sp<android::MetaData>&, bool, audio_stream_type_t) No sample bit depth info in meta data
E/AudioPolicyManager(  263): isOffloadSupported: stream_type != MUSIC, returning false
I/FFMPEG  (  263):     Stream #0:0: Audio: vorbis, 44100 Hz, mono, fltp, 239 kb/s
I/FFmpegExtractor(  263): adjust mime(application/ogg -> audio/vorbis)
D/FFmpegExtractor(  263): ffmpeg detected media content as 'audio/vorbis' with confidence 0.08
W/Utils   (  263): bool android::canOffloadStream(const android::sp<android::MetaData>&, bool, const android::sp<android::MetaData>&, bool, audio_stream_type_t) No sample bit depth info in meta data
E/AudioPolicyManager(  263): isOffloadSupported: stream_type != MUSIC, returning false
I/NuPlayer(  263): Could not offload audio decode, pcm offload decided :0
W/Utils   (  263): bool android::canOffloadStream(const android::sp<android::MetaData>&, bool, const android::sp<android::MetaData>&, bool, audio_stream_type_t) No sample bit depth info in meta data
E/AudioPolicyManager(  263): isOffloadSupported: stream_type != MUSIC, returning false
I/ActivityManager(  852): Start proc 1308:org.cyanogenmod.audiofx/u0a0 for added application org.cyanogenmod.audiofx
E/AudioPolicyManager(  263): getDeviceForStrategy() speaker device not found for STRATEGY_SONIFICATION
E/AudioPolicyManager(  263): getDeviceForStrategy() speaker device not found for STRATEGY_SONIFICATION
E/AudioPolicyManager(  263): getDeviceForStrategy() speaker device not found for STRATEGY_SONIFICATION
E/AudioPolicyManager(  263): getDeviceForStrategy() speaker device not found for STRATEGY_SONIFICATION
E/AudioPolicyManager(  263): getDeviceForStrategy() no device found for STRATEGY_TRANSMITTED_THROUGH_SPEAKER
E/AudioFlinger(  263): createEffect() unknown output thread
E/AudioEffect( 1308): set(): AudioFlinger could not create effect, status: -22
E/AudioEffects-JNI( 1308): AudioEffect initCheck failed -4
E/AudioEffect-JAVA( 1308): Error code -4 when initializing AudioEffect.
E/HeadsetService( 1308):    at android.media.audiofx.AudioEffect.<init>(AudioEffect.java:404)
E/HeadsetService( 1308):    at android.media.audiofx.Equalizer.<init>(Equalizer.java:139)
E/HeadsetService( 1308):    at org.cyanogenmod.audiofx.HeadsetService$EffectSet.<init>(HeadsetService.java:87)
E/HeadsetService( 1308):    at org.cyanogenmod.audiofx.HeadsetService.saveDefaults(HeadsetService.java:414)
E/HeadsetService( 1308):    at org.cyanogenmod.audiofx.HeadsetService.onCreate(HeadsetService.java:331)
```

**Comment by xen0n** [comment]
# AUDIO WORKING!

Huge thanks to @axet for the thought of just stubbing out the functions (the implementation can be tracked to [this file](https://github.com/axet/android_device_mt6592/blob/master/audio/audio.cpp); my efforts of properly merging the MTK bits failed due to the sheer amount of MTK code, [in a previous project]().)

Relevant commits:
- xen0n/local_manifests_arale@c0aaada
- xen0n/android_frameworks_av_mtk@a00acd6
- xen0n/android_device_meizu_arale@34864f3
- xen0n/android_vendor_meizu_arale@0408ee3
